import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='p-4 flex items-center justify-center flex-col w-full'>
          <Navbar />
           <div className='mt-8 w-[80%]'>
            {children}
           </div>
        </div>
        </body>
    </html>
  )
}
